"""
Backward-compatible facade for Extract Email.

Prefer importing from app.services.extract_email directly.
"""
from app.services.extract_email import (
    BUCKETS as _BUCKETS,
    MAX_SHEETS as _MAX_SHEETS,
    TAG_PREFIX as _TAG_PREFIX,
    SheetUnit,
    SourceCtx as _SourceCtx,
    analyse_upload,
    analyse_units as _analyse_units,
    extract_prompt as _extract_prompt,
    boost_sheet_from_hints as _boost_sheet_from_hints,
    build_result as _result,
    clean_dates as _clean_dates,
    collect_units as _collect_units,
    content_hash as _content_hash,
    detect_approval as _detect_approval,
    extract_full_email,
    extract_upload,
    group_sheets as _group_sheets,
    infer_from_filename as _infer_from_filename,
    is_native_file_unit as _is_native_file_unit,
    merge_thread_units as _merge_thread_units,
    mark_no_sheets as _mark_no_sheets,
    normalize_sheet as _normalize_sheet,
    preview_llm_egress,
    sanitize_body_sheet as _sanitize_body_sheet,
    stage_groups as _stage_groups,
    staged_message as _staged_message,
    system_prompt,
    union_group_buckets as _union_group_buckets,
    unit_from_bytes as _unit_from_bytes,
    units_from_upload as _units_from_upload,
)

__all__ = [
    "SheetUnit",
    "_BUCKETS",
    "_MAX_SHEETS",
    "_TAG_PREFIX",
    "_SourceCtx",
    "_analyse_units",
    "_extract_prompt",
    "_boost_sheet_from_hints",
    "_clean_dates",
    "_collect_units",
    "_content_hash",
    "_detect_approval",
    "_group_sheets",
    "_infer_from_filename",
    "_is_native_file_unit",
    "_mark_no_sheets",
    "_merge_thread_units",
    "_normalize_sheet",
    "_result",
    "_sanitize_body_sheet",
    "_stage_groups",
    "_staged_message",
    "_union_group_buckets",
    "_unit_from_bytes",
    "_units_from_upload",
    "analyse_upload",
    "extract_full_email",
    "extract_upload",
    "preview_llm_egress",
    "system_prompt",
]
